# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Upload deploy-quickstart.tar
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create Archive
        run: tar -caf deploy-quickstart.tar -C deploy/docker/quickstart/ .
      - name: Upload Archive
        run: gh release upload ${{ github.ref_name }} deploy-quickstart.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
