name: Test Controller Startup

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'website/**'
      - 'docker-autoheal/**'
      - 'sdk/**'
      - 'deploy/charts/**'
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'website/**'
      - 'docker-autoheal/**'
      - 'sdk/**'
      - 'deploy/charts/**'
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        controller:
          - docker
          - kubernetes
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache-dependency-path: |
            go.sum
      - name: Build Controller
        run: go build -o dist/${{ matrix.controller }}-controller ./cmd/controller/${{ matrix.controller }}
      - name: Test Controller Startup
        run: |
          echo "run ${{ matrix.controller }} controller with timeout $TIMEOUT"
          if timeout "$TIMEOUT" bash -c '
            {
              while read -r line; do
                echo "controller> $line"
                if [[ "$line" == *"controller is starting"* ]]; then
                  exit 0
                fi
              done
            } < <("./dist/${{ matrix.controller }}-controller" 2>&1)
            echo "Controller quit unexpectedly"
            exit 1
          '; then
            echo "Controller startup successful"
            exit 0
          else
            echo "Controller did not start within $TIMEOUT or quit unexpectedly"
            exit 1
          fi
        env:
          TIMEOUT: '10s'
          DISTR_TARGET_ID: '95a53f00-a01e-414e-98fd-9e1cbf3553d9'
          DISTR_TARGET_SECRET: '00000000000000000000000000000000'
          DISTR_LOGIN_ENDPOINT: http://localhost:8080/api/v1/controller/login
          DISTR_MANIFEST_ENDPOINT: http://localhost:8080/api/v1/controller/manifest
          DISTR_RESOURCE_ENDPOINT: http://localhost:8080/api/v1/controller/resources
          DISTR_STATUS_ENDPOINT: http://localhost:8080/api/v1/controller/status
          DISTR_METRICS_ENDPOINT: http://localhost:8080/api/v1/controller/metrics
          DISTR_DEPLOYMENT_METRICS_ENDPOINT: http://localhost:8080/api/v1/controller/deployments
          DISTR_LOGS_ENDPOINT: http://localhost:8080/api/v1/controller/logs
          DISTR_DEPLOYMENT_TARGET_LOGS_ENDPOINT: http://localhost:8080/api/v1/controller/deployment-target-logs
          DISTR_CONTROLLER_INTERVAL: 5s
          DISTR_REGISTRY_HOST: localhost:8585
